### 1. 장바구니 추가
POST http://localhost:8080/api/cart/items
Content-Type: application/json

{
  "userId": 1,
  "optionId": 1,
  "quantity": 1
}


### 2. 장바구니 조회
GET http://localhost:8080/api/cart?userId=1


### 3. 주문 생성
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "userId": 1,
  "shippingAddressSnapshot": "경기도 수원시 테스트 주소"
}


### 4. mock 결제
POST http://localhost:8080/api/payments/mock
Content-Type: application/json

{
  "orderId": 6,
  "paymentMethod": "MOCK_CARD"
}


### 5. 내가 구매한 상품 목록 조회
GET http://localhost:8080/api/orders/users/1/items


### 6. 리셀 등록
POST http://localhost:8080/api/resells
Content-Type: application/json

{
  "sellerId": 1,
  "orderItemId": 6,
  "resellPrice": 45000,
  "conditionDescription": "2회 착용, 오염 없음"
}


### 7. 리셀 목록 조회
GET http://localhost:8080/api/resells


### 8. 리셀 상세 조회
GET http://localhost:8080/api/resells/2


### 9. 리셀 가격 제안
POST http://localhost:8080/api/resells/2/offers
Content-Type: application/json

{
  "buyerId": 2,
  "offerPrice": 40000
}


### 10. 리셀 바로 구매
POST http://localhost:8080/api/resells/2/purchase
Content-Type: application/json

{
  "buyerId": 2
}

### 11. 내가 등록한 리셀 상품 목록
GET http://localhost:8080/api/resells/sellers/1


### 12. 특정 리셀 상품에 들어온 가격 제안 목록
GET http://localhost:8080/api/resells/2/offers


### 13. 구매자가 보낸 가격 제안 목록
GET http://localhost:8080/api/resells/buyers/2/offers


### 14. 구매자의 리셀 구매 내역
GET http://localhost:8080/api/resells/buyers/2/transactions

### 15. 중복 리셀 등록 방지 테스트
POST http://localhost:8080/api/resells
Content-Type: application/json

{
  "sellerId": 1,
  "orderItemId": 1,
  "resellPrice": 45000,
  "conditionDescription": "중복 등록 테스트"
}


### 16. SOLD 상품 가격 제안 방지 테스트
POST http://localhost:8080/api/resells/2/offers
Content-Type: application/json

{
  "buyerId": 2,
  "offerPrice": 40000
}


### 17. SOLD 상품 재구매 방지 테스트
POST http://localhost:8080/api/resells/2/purchase
Content-Type: application/json

{
  "buyerId": 2,
  "purchasePrice": 45000
}


### 18. 자기 상품 가격 제안 방지 테스트
POST http://localhost:8080/api/resells/2/offers
Content-Type: application/json

{
  "buyerId": 1,
  "offerPrice": 40000
}

### 19. 리셀 상품 수정 테스트
PATCH http://localhost:8080/api/resells/3
Content-Type: application/json

{
  "sellerId": 1,
  "resellPrice": 52000,
  "conditionDescription": "1회 착용, 오염 없음, 상태 매우 좋음"
}


### 20. 리셀 상품 판매 취소 테스트
PATCH http://localhost:8080/api/resells/3/cancel?sellerId=1


### 21. 취소된 리셀 상품 상세 조회
GET http://localhost:8080/api/resells/3